# NOTE:
# This builder configuration is NOT used to build any official binary.
# To see the builder manifests used for official binaries,
# check https://github.com/open-telemetry/opentelemetry-collector-releases

dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/oteltestbedcol
  name: oteltestbedcol
  description: OpenTelemetry Collector binary for testbed only tests.
  version: 0.146.0-dev
  output_path: ./cmd/oteltestbedcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.146.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/opensearchexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/otelarrowexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sapmexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/stefexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/syslogexporter v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter v0.146.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.146.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.146.2-0.20260219223409-66996adfaaf7
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/carbonreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otelarrowreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/signalfxreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/stefreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/udplogreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.146.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.52.1-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.52.1-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.52.1-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.52.1-0.20260219223409-66996adfaaf7
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.52.1-0.20260219223409-66996adfaaf7

# When using `make genoteltestbedcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# Contrib modules.
replaces:
